[package]
name = "mark-marks/riptide"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
    "README.md",
]

[dependencies]
Signal = "red-blox/signal@2.0.2"
Future = "red-blox/future@1.0.1"
Ratelimit = "red-blox/ratelimit@1.0.1"
Guard = "red-blox/guard@1.0.1"
Spawn = "red-blox/spawn@1.0.0"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
